apiVersion: v1
kind: BuildConfig
metadata:
  name: openshift-jenkins-shared-library-build
spec:
  runPolicy: Parallel
  source:
    git:
      ref: master
      uri: https://github.com/defcyy/openshift-jenkins-shared-library.git
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile.build
    type: JenkinsPipeline